name: dresdenzero

services:
    wahlrechner:
        image: ghcr.io/wahlrechner/wahlrechner:latest
        command: bash -c 'docker/wait-for-it/wait-for-it.sh db:3306 -t 120 -- docker/startup-production.sh'
        restart: always
        networks:
            - internal_network
        volumes:
            - ./data/static:/code/assets/
            - ./data/media:/code/media/
            - ./data/logs/wahlrechner:/code/logs/
            - ./data/migrations/wahlrechner:/code/wahlrechner/migrations
            - ./themes:/code/themes
            - ./data/stats:/code/wahlrechner/stats
        env_file:
            - ./config/config.env
        depends_on:
            - db

    db:
        image: mariadb
        restart: always
        networks:
            - internal_network
        env_file:
            - ./config/config.env
        volumes:
            - ./data/mysql:/var/lib/mysql

    web:
        build:
            context: web/apache
        restart: always
        networks:
            - internal_network
            - external_network
        ports:
            - "127.0.0.1:5000:443"
        volumes:
            - ./data/static:/wahlrechner/static
            - ./data/media:/wahlrechner/media
            - ./web/cert:/wahlrechner/cert
            - ./data/logs/apache:/usr/local/apache2/logs
            - /etc/letsencrypt:/etc/letsencrypt

networks:
    external_network:
    internal_network:
        internal: true
